---
title: "Distance, Mobility, and Mode Choice : A Spatial Analysis of School Travel Behaviour in Ireland"
authors:
  - name: Sananthaa Jagadesan Sethamaraikannan
    department: Department of Mathematics & Statistics
    affiliation: University of Galway
    location: Galway,Ireland.
    email: sananthaajagadesan@gmail.com
  - name: Judith Beltran Lopez
    department: Department of Mathematics & Statistics
    affiliation: University of Galway
    location: Galway,Ireland
    email:
abstract: |
  In Ireland, whether a child can walk or cycle to school depends heavily on where they live, something that has been described as a postcode lottery. This study investigates whether the location of schools and how easily they can be reached explains differences in active travel rates across Ireland. We used data from the 2022 Census, the Department of Education, and OpenStreetMap to measure school accessibility for over 16,000 small areas across Ireland. Two methods were used to measure accessibility-kriging, which estimates the density of school places across space, and r5r, which calculates how many school places can be reached within a given walking or cycling time using the real road network. We then used Bayesian Beta regression to model the relationship between accessibility and the proportion of children walking or cycling to school.
keywords:
  -sss
bibliography: references.bib
biblio-style: unsrt
header-includes:
  - \providecommand{\pandocbounded}[1]{#1}
  - \usepackage{booktabs}
  - \usepackage{array}
output: rticles::arxiv_article
---

# Introduction

Here goes an introduction text

## 1.1 Background
\label{sec:headings}

You can use directly LaTeX command or Markdown text. 

LaTeX command can be used to reference other section. See Section \ref{sec:headings}.
However, you can also use **bookdown** extensions mechanism for this.

## 1.2 The Postcode Lottery Argument from the article


## 1.3 Research Objectives

# 2 Data

## 2.1 School Data

## 2.2 Census Data

## 2.3 Study Area

# 3 Methods

## 3.1 School Place Density:Kriging

## 3.2 Travel Time Accessibility:r5r

## 3.3 Demographic Variables:ILR Transformation

## 3.4 Statistical Model:Bayesian Beta Regression

## 3.5 Normalisation by School:Age Population

# 4 Results

## 4.1 Spatial Distribution of Schools

## 4.2 Walking and Cycling Accessibility: travel time

## 4.3 Kriging vs Travel Time Comparison

## 4.4 Model Results — Urban Areas,rural if possible

## 4.5 Effect of Walking Accessibility on Active Travel

# 5 Discussion

## 5.1 Interpretation of Results

## 5.2 Limitations

## 5.3 Comparison with the article

# 6 Conclusions

# 7 References