---
title: "eda_census"
output: html_document
---


```{r}
library(tidyverse)
library(janitor)
#library(DataExplorer)

df <- read_csv("../data/SAP2022T11T1TOWN22.20251128T151123.csv") %>%
  clean_names()

df_clean <- df %>%
  filter(means_of_travel != "Not stated")

df_clean <- df_clean %>%
  mutate(
    health_group = if_else(
      means_of_travel %in% c("On Foot", "Bicycle"),
      "Healthy",
      "Not healthy"
    )
  )


head(df_clean)
glimpse(df_clean)
```



```{r}
summary(df_clean)

```




```{r}
df_clean %>% summarise(
  n_towns = n_distinct(towns_2022),
  n_means = n_distinct(means_of_travel),
  n_years = n_distinct(census_year)
)
```





```{r}
df_clean %>%
  group_by(towns_2022, means_of_travel) %>%
  summarise(total = sum(value), .groups = "drop") %>%
  arrange(desc(total)) %>%
  head(20)
```




```{r}
df_clean %>%
  group_by(means_of_travel) %>%
  summarise(total = sum(value), .groups = "drop") %>%
  mutate(percentage = total / sum(total) * 100) %>%
  ggplot(aes(x = reorder(means_of_travel, percentage), y = percentage)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    title = "Percentage of Usually Resident Population by Travel Mode",
    x = "Means of Travel",
    y = "Percentage (%)"
  )

```


```{r}
unique(df_clean$means_of_travel)
```



```{r}

df_clean %>%
  group_by(health_group) %>%
  summarise(total = sum(value), .groups = "drop") %>%
  mutate(percentage = total / sum(total) * 100) %>%
  ggplot(aes(x = reorder(health_group, percentage), y = percentage)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    title = "Percentage of Usually Resident Population by Health Group",
    x = "Health Group",
    y = "Percentage (%)"
  )


```


```{r}

df_clean <- df_clean %>%
  mutate(county = str_extract(towns_2022, "(?<=,).*"))
df_plot_counties <- df_clean%>% count(county, health_group, name="count")%>%mutate(percentage = count / sum(count))

df_plot_counties
```


```{r}
library(ggplot2)
library(scales)
library(plotly)

p <- ggplot(df_plot_counties, aes(x = county, y = percentage, fill = health_group)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = percent_format()) +
  theme_minimal()

ggplotly(p)%>%layout(xaxis=list(tickangle= -90))

```


```{r}

```


```{r}

```


```{r}

```