---
title: "EDA Schools"
author: "Judith Beltrán"
date: "2025-11-17"
output: html_document
---

```{r}
library(readxl)
library(dplyr)

schools_df <- read_excel("Data_on_Individual_Schools_Mainstream_2024_25.xlsx", sheet=2)
schools_df <- schools_df%>%rename("Roll_Number" = "Roll Number")%>%rename("longitude" = "School Longitude")%>%rename("latitude" = "School Latitude")


schools_df <- schools_df %>%
  rename(
    AcademicYear = `Academic Year (Enrolment)`,
    SchoolName   = `Official Name`
  )
```

```{r}
library(sf)
library(rnaturalearth)
library(ggplot2)

world <- ne_countries(scale = "medium", returnclass = "sf")

ireland <- world[world$admin == "Ireland", ]
```
```{r}

schools_df_clean <- schools_df[complete.cases(schools_df[, c("longitude", "latitude")]), ] # clean null

schools_sf <- st_as_sf(
  schools_df_clean,
  coords = c("longitude", "latitude"),
  crs = 4326
)

# Plot
ggplot() +
  geom_sf(data = ireland) +
  geom_sf(data = schools_sf) +
  labs(
    title = "Schools in Ireland",
    subtitle = "Points located using coordinates"
  )

```

```{r}
ggplot(schools_df, aes(x = `School Type`)) +
  geom_bar() +
  coord_flip() +
  labs(
    title = "Number of schools by School Type",
    x = "School Type",
    y = "Number of schools"
  )

```

```{r}
ggplot(schools_df, aes(x = Female, y = Male)) +
  geom_point(alpha = 0.5) +
  labs(
    title = "Female vs Male enrolment per school",
    x = "Female enrolment",
    y = "Male enrolment"
  )

```



```{r}

schools_sf <- st_as_sf(
  schools_df_clean,
  coords = c("longitude", "latitude"),
  crs = 4326,
  remove = FALSE
)

ggplot() +
  geom_sf(data = ireland) +
  geom_sf(data = schools_sf, aes(colour = `School Level`), size = 0.7, alpha = 0.8) +
  labs(title = "Schools in Ireland by Level")

```
